### ISSUE TITLE
Travis CI 빌드 명령어 수정하기  & CI/CD 구축하기

### ISSUE THREAD

**Issue by YoungHo-Jo** [cheGaebara/joolinee#21]
* React Native buid

* Spring build

* Django build

## jenkins로 CI/~~CD~~ 구축하기  

---
집에서 자고있는 라즈베리 파이 일시키자.

---

## 해야할일 ( ~ 06.20)  

- [ ] : 라즈베리에 jenkins 빌드서버 만들기
- [ ] : 자체 spring MVC (gradle) + react build 구축연습
- [ ] : 자체 spring MVC (maven) + react build 구축연습
- [ ] : 우리 프로젝트 github과 연동

**Comment by Gyeongmin-lucid** [comment]
CI/CD 툴을 jenkins로 바꾸려고합니다.
Travis가 github과의 연동이나 편의성 기타 여러면에서 좋으나,
Jenkin의 범용성, 그리고 현업은 Github구조가 아니라 jenkins를 사용한다는 점을 토대로
공부를 해본다는 목적하에 Jenkin를 우리 프로젝트에 도입하고자 하는데
어떻게 생각하나요?

**Comment by Gyeongmin-lucid** [comment]
# jenkins로 CI/CD 구축하기
---------------------------------------------------
집에서 자고있는 라즈베리 파이 일시키자.
---------------------------------------------------

## 해야할일 ( ~ 06.20)

-[ ] : 라즈베리에 jenkins 빌드 환경 구축
-[ ] : 자체 spring MVC (gradle) + react build 구축연습
-[ ] : 자체 spring MVC (maven) + react build 구축연습
